OUT_ZIP=SlackwareWSL.zip
LNCR_EXE=Slackware.exe

DLR=curl
DLR_FLAGS=-L
LNCR_ZIP_URL=https://github.com/yuk7/wsldl/releases/download/22020900/icons.zip
LNCR_ZIP_EXE=Slackware.exe

all: $(OUT_ZIP)

zip: $(OUT_ZIP)
$(OUT_ZIP): ziproot
	@echo -e '\e[1;31mBuilding $(OUT_ZIP)\e[m'
	cd ziproot; zip ../$(OUT_ZIP) *

ziproot: Launcher.exe rootfs.tar.gz
	@echo -e '\e[1;31mBuilding ziproot...\e[m'
	mkdir ziproot
	cp Launcher.exe ziproot/${LNCR_EXE}
	cp rootfs.tar.gz ziproot/

exe: Launcher.exe
Launcher.exe: icons.zip
	@echo -e '\e[1;31mExtracting Launcher.exe...\e[m'
	unzip icons.zip $(LNCR_ZIP_EXE)
	mv $(LNCR_ZIP_EXE) Launcher.exe

icons.zip:
	@echo -e '\e[1;31mDownloading icons.zip...\e[m'
	$(DLR) $(DLR_FLAGS) $(LNCR_ZIP_URL) -o icons.zip

rootfs.tar.gz: rootfs
	@echo -e '\e[1;31mBuilding rootfs.tar.gz...\e[m'
	cd rootfs; sudo bsdtar -zcpf ../rootfs.tar.gz `sudo ls`
	sudo chown `id -un` rootfs.tar.gz

rootfs: base.tar
	@echo -e '\e[1;31mBuilding rootfs...\e[m'
	mkdir rootfs
	sudo bsdtar -zxpf base.tar -C rootfs
	@echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." | sudo tee rootfs/etc/resolv.conf > /dev/null
	sudo cp wsl.conf rootfs/etc/wsl.conf
	sudo cp bash_profile rootfs/root/.bash_profile
	sudo cp bashrc rootfs/etc/skel/.bashrc
	sudo cp bashprofile rootfs/etc/skel/.bash_profile
	sudo chmod +x rootfs

base.tar:
	@echo -e '\e[1;31mExporting base.tar using docker...\e[m'
	docker run --net=host --name slackware vbatts/slackware:current /bin/bash -c "sed -i 's/http:\/\/slackware.osuosl.org\/slackware64-current\//http:\/\/slackware.osuosl.org\/slackware64-15.0\//g' /etc/slackpkg/mirrors; sed -i 's/linux/xterm/g' /etc/profile.d/term.sh; wget --no-check-certificate https://slack.conraid.net/repository/slackware64-current/figlet/figlet-2.2.5-x86_64-1cf.txz; wget --no-check-certificate https://telkomuniversity.dl.sourceforge.net/project/slackpkgplus/slackpkg%2B-1.8.0-noarch-2mt.txz; installpkg figlet-2.2.5-x86_64-1cf.txz slackpkg+-1.8.0-noarch-2mt.txz; rm slackpkg+-1.8.0-noarch-2mt.txz figlet-2.2.5-x86_64-1cf.txz; echo 'YES' | slackpkg update gpg; slackpkg update; slackpkg upgrade-all; slackpkg install acl acpid attr bash-completion bc bind binutils bison brotli btrfs-progs ca-certificates cpio curl cyrus-sasl dcron devs diffstat dosfstools ebtables ed elfutils elogind eudev exfatprogs f2fs-tools flex floppy gc git gcc gettext-tools glib glib2 glibc glibc-profile glibc-i18n glibc-zoneinfo gnutls gpm gptfdisk groff guile haveged hdparm hostname hwdata htop inih infozip inotify-tools iputils json-c kbd kmod lbzip2 less libarchive libblockdev libbytesize libcap libgudev libtool libunwind libusb libusb-compat libxml2 libuv lmdb logrotate lsof lvm2 lz4 lzip lzlib m4 make man mcelog minicom mlocate mtx nano ncompress ndctl neofetch network-scripts nghttp2 ntp oniguruma openssh openssl-solibs pam parted pciutils pcmciautils pcre pinentry perl pkg-config plzip readline reiserfsprogs rpm2tgz rsync screen sdparm sharutils smartmontools splitvt squashfs-tools socat strace sudo sysklogd terminus-font texinfo udisks udisks2 unarj usb_modeswitch usbutils vim whois xxHash zlib zoo zstd"
	docker export --output=base.tar slackware
	docker rm -f slackware

clean:
	@echo -e '\e[1;31mCleaning files...\e[m'
	-rm ${OUT_ZIP}
	-rm -r ziproot
	-rm Launcher.exe
	-rm icons.zip
	-rm rootfs.tar.gz
	-sudo rm -r rootfs
	-rm base.tar
	-docker rmi -f vbatts/slackware:current
