OUT_ZIP=SlackwareWSL.zip
LNCR_EXE=Slackware.exe

DLR=curl
DLR_FLAGS=-L
LNCR_ZIP_URL=https://github.com/yuk7/wsldl/releases/download/22020900/icons.zip
LNCR_ZIP_EXE=Slackware.exe

all: $(OUT_ZIP)

zip: $(OUT_ZIP)
$(OUT_ZIP): ziproot
	@echo -e '\e[1;31mBuilding $(OUT_ZIP)\e[m'
	cd ziproot; zip ../$(OUT_ZIP) *

ziproot: Launcher.exe rootfs.tar.gz
	@echo -e '\e[1;31mBuilding ziproot...\e[m'
	mkdir ziproot
	cp Launcher.exe ziproot/${LNCR_EXE}
	cp rootfs.tar.gz ziproot/

exe: Launcher.exe
Launcher.exe: icons.zip
	@echo -e '\e[1;31mExtracting Launcher.exe...\e[m'
	unzip icons.zip $(LNCR_ZIP_EXE)
	mv $(LNCR_ZIP_EXE) Launcher.exe

icons.zip:
	@echo -e '\e[1;31mDownloading icons.zip...\e[m'
	$(DLR) $(DLR_FLAGS) $(LNCR_ZIP_URL) -o icons.zip

rootfs.tar.gz: rootfs
	@echo -e '\e[1;31mBuilding rootfs.tar.gz...\e[m'
	cd rootfs; sudo bsdtar -zcpf ../rootfs.tar.gz `sudo ls`
	sudo chown `id -un` rootfs.tar.gz

rootfs: base.tar
	@echo -e '\e[1;31mBuilding rootfs...\e[m'
	mkdir rootfs
	sudo bsdtar -zxpf base.tar -C rootfs
	@echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." | sudo tee rootfs/etc/resolv.conf > /dev/null
	sudo cp bash_profile rootfs/root/.bash_profile
	sudo cp bashrc rootfs/etc/skel/.bashrc
	sudo cp bashprofile rootfs/etc/skel/.bash_profile
	sudo chmod +x rootfs

base.tar:
	@echo -e '\e[1;31mExporting base.tar using docker...\e[m'
	docker run --net=host --name slackware vbatts/slackware:current /bin/bash -c "sed -i 's/http:\/\/slackware.osuosl.org\/slackware64-current\//http:\/\/slackware.osuosl.org\/slackware64-15.0\//g' /etc/slackpkg/mirrors; echo 'YES' | slackpkg update gpg; slackpkg update; slackpkg upgrade-all; slackpkg clean-system; slackpkg install acl attr bash-completion binutils bc ca-certificates cpio curl elogind flex gc git gcc groff guile htop infozip iputils libcap libunwind m4 make man nano neofetch openssh parted pkg-config readline reiserfsprogs sharutils squashfs-tools socat sudo usbutils vim; wget --no-check-certificate https://slack.conraid.net/repository/slackware64-current/figlet/figlet-2.2.5-x86_64-1cf.txz; wget --no-check-certificate https://telkomuniversity.dl.sourceforge.net/project/slackpkgplus/slackpkg%2B-1.8.0-noarch-2mt.txz; installpkg figlet-2.2.5-x86_64-1cf.txz slackpkg+-1.8.0-noarch-2mt.txz; rm slackpkg+-1.8.0-noarch-2mt.txz figlet-2.2.5-x86_64-1cf.txz"
	docker export --output=base.tar slackware
	docker rm -f slackware

clean:
	@echo -e '\e[1;31mCleaning files...\e[m'
	-rm ${OUT_ZIP}
	-rm -r ziproot
	-rm Launcher.exe
	-rm icons.zip
	-rm rootfs.tar.gz
	-sudo rm -r rootfs
	-rm base.tar
	-docker rmi -f vbatts/slackware:current
